services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: app
    volumes:
      - ../db/create.sql:/docker-entrypoint-initdb.d/init.sql